### ISSUE TITLE
travis still being annoying

### ISSUE THREAD

**Issue by clux** [lalbuild/lal#30]
This is the current mess:

```yaml
script:
- cargo clean
- if [ "$TRAVIS_PULL_REQUEST" = "true" ]; then cargo build; fi
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then docker run --rm -v $PWD:/volume -w /volume -t clux/muslrust cargo build --release; fi
- if [ "$TRAVIS_PULL_REQUEST" = "true" ]; then cargo test; fi
- if [ "$TRAVIS_PULL_REQUEST" = "true" ]; then cargo doc --no-deps; fi
branches:
  only:
  - master
  - /^v.*$/
before_deploy:
  - sudo chown -R $USER:$USER target
  - ldd target/x86_64-unknown-linux-musl/release/lal || true
  - mkdir ARTIFACT/{bin,share/lal} -p
  - mv target/x86_64-unknown-linux-musl/release/lal ARTIFACT/bin/
  - cp lal.complete.sh ARTIFACT/share/lal/
  - tar czf lal.tar.gz --transform=s,^ARTIFACT/,, $(find ARTIFACT/ -type f -o -type l)
deploy:
  provider: releases
  file: lal.tar.gz
  skip_cleanup: true
  on:
    tags: true
  api_key: ...
after_script: |
  if [ "$TRAVIS_PULL_REQUEST" = "false" ] && [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    bash <(curl -sSL https://raw.githubusercontent.com/xd009642/tarpaulin/master/travis-install.sh)
    sudo chown -R $USER:$USER target
    cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
  fi
```

unfortunately when you push to a branch, that's NOT a TRAVIS_PULL_REQUEST, but a push to a non-master branch, even if it's also in a PR. Note the already crazy branch filtering that includes a semver regex to get travis to only upload releases on a new tag.

Hacks on top of hacks. Maybe try to do this with circleci?
